deployment:
  tasks:
    - export DEPLOYPATH=/home/xjzevedw/public_html # Tambahkan /<nama_folder_aplikasi> jika diperlukan
    - /bin/cp -r * $DEPLOYPATH # Salin semua file dan folder secara rekursif ke $DEPLOYPATH
